version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "03:00"

  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: "monthly"
      time: "03:00"
