name: 'wecom-bot-notify'
description: 'A GitHub Action that sends message to wecom bot'
author: 'akinocccc'
inputs:
  key: 
    required: true
    description: 'WeCom bot hook key'
  type:
    required: true
    description: 'Message type'
  content:
    required: true
    description: 'Message content'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'thumbs-up'
  color: 'green'
