name: 'Notify'
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Context Variables
        env:
          Repository: ${{ github.event.repository.name }}
          Branch: ${{ github.event.workflow_run.head_branch }}
          Message: ${{ github.event.workflow_run.head_commit.message }}
          Committer: ${{ github.event.workflow_run.head_commit.committer.name }}
        run: |
          echo "Repository: ${{ github.event.repository.name }}"
          echo "Workflow: ${{ github.event }}"
          echo "Branch: ${{ env.Branch }}"
          echo "Commit Message: ${{ env.Message }}"
          echo "Committer: ${{ env.Committer }}"
      - uses: ./
        with:
          type: markdown # text, markdown, image, news, template_card
          key: ${{ secrets.WECOM_BOT_KEY }} # Your key of wecom bot hook
          content: |
            # Hello all, I will release ${{ github.event.repository.name }} ${{ github.workflow }} with branch ${{ github.event.workflow_job.head_branch }}, please note that.
            > ${{ github.event.head_commit.message }}
            > pushed by ${{ github.event.head_commit.committer.name }}