name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@main
      - uses: ./
        with:
          type: markdown # text, markdown, image, news, template_card
          key: ${{ secrets.WECOM_BOT_KEY }} # Your key of wecom bot hook
          content: |
            # Hello all, I will release ${{ github.event.repository.name }} ${{ github.workflow }}, please note that.
            > ${{ github.event.head_commit.message }}
            > pushed by ${{ github.event.head_commit.committer.name }}
      
      - name: Print output    
        run: |
          echo "type: ${{ steps.notify.outputs['type'] }}"
          echo "message: ${{ steps.notify.outputs['message'] }}"
          echo "result: ${{ steps.notify.outputs['res'] }}"
          echo "error: ${{ steps.notify.outputs['error'] }}"
